# Generated by Django 2.0.5 on 2018-05-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='meeting_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
