# Generated by Django 2.0.5 on 2018-05-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0002_studygroup_meeting_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroup',
            old_name='meetings_days',
            new_name='meeting_days',
        ),
    ]
