# Generated by Django 2.0.5 on 2018-05-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0003_auto_20180521_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studybuddy.StudyGroup'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studybuddy.Student'),
        ),
    ]
