# Generated by Django 2.0.5 on 2018-05-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0003_auto_20180530_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='meeting_days_2',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='1', max_length=9),
        ),
    ]
