# Generated by Django 2.0.5 on 2018-05-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0004_auto_20180524_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
